### ISSUE TITLE
Include the minified version of require.js in the npm package

### ISSUE THREAD

**Issue by lukasbestle** [requirejs/requirejs-npm#6]
Since I'm using `npm` as my frontend package manager for simplicity (it's integrated into my build scripts), I'd like to get `require.js` with `npm` using `npm install requirejs`.

That works, but unfortunately the package does not include the minified version. While it isn't needed for backend (node) use-cases, it makes sense if using `npm` as frontend package manager as I do.
It would be awesome if you could include the minified version in this package in future releases as well.

**Comment by jrburke** [comment]
No plans to provide a minified version in the package. It is pretty easy to generate it yourself though.

After running the `npm install requirejs`, you can run `uglifyjs node_modules/requirejs/require.js -c -m -o node_modules/requirejs/require.min.js` (assuming uglifyjs has been globally installed, adjust to project-specific locations as necessary).

**Comment by lukasbestle** [comment]
Thanks for your fast response.

Alright, that definitely works. It removes copyright and license, but if that's the official way, I will use that.

**Comment by PyvesB** [comment]
@lukasbestle I believe that there are uglifyjs options to preserve License/Copyright comments. In particular, using `--comments "some"` should do the trick, as the license comment in _require.js_ contains a supported `@license` tag. See [this section](https://www.npmjs.com/package/uglify-js#keeping-copyright-notices-or-other-comments) of the documentation for more information. 😉
