### ISSUE TITLE
Move source files one level up

### ISSUE THREAD

**Issue by shariffy** [requirejs/requirejs-npm#7]
`npm` has a great feature to point a dependency's location directly to a git repo and branch, which is really handy when forking and contributing to an npm package (i.e. to use the fixed up fork temporarily). But that `npm` feature cannot look into subdirectories [AFAIK](https://github.com/npm/npm/issues/2974).

My point is less about making life easier for forkers (one can easily fix this within the fork) but if `package.json` is expected to be at the root as a standard, following the convention can't be a bad thing.

Most likely there are dependencies in the build workflow to land this change but if one can point to/list those, I'll be happy to help to make this happen.

**Comment by jrburke** [comment]
I am not sure how this helps: this repo only ever contains release versions of requirejs for npm, and those are published to the npm registry.

I do try to keep https://github.com/jrburke/r.js/blob/master/dist/r.js up to date when any source commits done for r.js in particular. I have pointed people to fetching specific commit versions for that URL for testing early fixes. Maybe that is enough?

Going to close, as I do not use this repo to hold intermediate releases, and I prefer people not looking to it for anything other than a staging area for publishing an artifact to the npm registry. However, feel free to continue discussion here.
